### ISSUE TITLE
hip joint selection question

### ISSUE THREAD

**Issue by mark-borg** [DeJaVoo/partial-openpose#1]
Hello,

Quite an interesting project. 
I am currently running your code and wish to ask something: does the existing algorithm work only with manually-selected hip joint? Thanks.

Mark

**Comment by dvirsegal** [comment]
Hi, thank you for the feedback,
You can manually create hip position but you should mimic openpose skeleton structure.
Since my algorithm is based on it and expect to the API signatures.

**Comment by mark-borg** [comment]
Thanks for your reply.
Do you have any plans of making the process fully automated in the future?

**Comment by dvirsegal** [comment]
No at the moment

**Comment by mark-borg** [comment]
thanks
